### ISSUE TITLE
Sanity check graph takes a long time to load

### ISSUE THREAD

**Issue by matt-graham** [SamDuffield/bayesian-traffic#7]
*Submitting as part of JOSS review openjournals/joss-reviews/issues/3651*

I really like the sanity check example in the documentation, however I think it may be worth using a different location than London to source the example graph as running

```Python
graph = ox.graph_from_place('London, UK')
```

takes around 8 minutes on my laptop and the lack of any progress updates from the `osmnx` package when executing `graph_from_place` made it a bit unclear initially if the interpreter had crashed. Swapping for a location that produces a smaller graph would still perform the same function of illustrating the inference algorithm is computing something sensible but without requiring so much patience from the user! If you prefer to keep the current example, I think it would then be worth at least putting a warning to expect the `osmnx` functions to take a long time to run.

**Comment by SamDuffield** [comment]
As a large portion of the anticipated use cases is in urban environments (most likely major cities such as London) I think leaving the example as is but adding a precautionary comment about `osmnx` loading times is the most useful for the user. (Also the `sample_route` function works better for larger areas as it is less likely to terminate early on reaching the edge of the area.)

I have added said warnings to the docs!

**Comment by matt-graham** [comment]
> As a large portion of the anticipated use cases is in urban environments (most likely major cities such as London) I think leaving the example as is but adding a precautionary comment about `osmnx` loading times is the most useful for the user. (Also the `sample_route` function works better for larger areas as it is less likely to terminate early on reaching the edge of the area.)

Those both seem good rationales for keeping the current example, thanks for the clarifications!

> I have added said warnings to the docs!

👍
